FROM richarvey/nginx-php-fpm:3.1.6

WORKDIR /var/www/html

COPY . /var/www/html

RUN composer install --no-dev --optimize-autoloader \
    && chown -R nginx:nginx /var/www/html/storage /var/www/html/bootstrap/cache